// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoinApi.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Models.Coins", b =>
                {
                    b.Property<int>("MonedaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("MonedaId");

                    b.ToTable("Coins");

                    b.HasData(
                        new
                        {
                            MonedaId = 1,
                            Descripcion = "Bitcoin",
                            ImagenUrl = "https://cdn.pixabay.com/photo/2021/04/30/16/47/btc-logo-6219386_960_720.png",
                            Valor = 10000.0
                        },
                        new
                        {
                            MonedaId = 2,
                            Descripcion = "Ethereum",
                            ImagenUrl = "https://cdn.icon-icons.com/icons2/3369/PNG/512/ethereum_coin_money_cryptocurrency_icon_210995.png",
                            Valor = 9000.0
                        },
                        new
                        {
                            MonedaId = 3,
                            Descripcion = "Cardano",
                            ImagenUrl = "https://www.pngall.com/wp-content/uploads/10/Cardano-Crypto-Logo-PNG-Free-Image.png",
                            Valor = 8000.0
                        },
                        new
                        {
                            MonedaId = 4,
                            Descripcion = "Tether",
                            ImagenUrl = "https://iconape.com/wp-content/files/ac/209643/png/tether-usdt-logo.png",
                            Valor = 7000.0
                        },
                        new
                        {
                            MonedaId = 5,
                            Descripcion = "Binance Coin",
                            ImagenUrl = "https://thumbs.dreamstime.com/z/s%C3%ADmbolo-de-oro-del-binance-crypto-la-moneda-aislado-en-el-fondo-blanco-137343964.jpg",
                            Valor = 6000.0
                        },
                        new
                        {
                            MonedaId = 6,
                            Descripcion = "Repple",
                            ImagenUrl = "https://previews.123rf.com/images/ryzhi/ryzhi1712/ryzhi171200070/91650546-moneda-de-oro-de-la-moneda-de-crypto-con-s%C3%ADmbolo-de-la-ondulaci%C3%B3n-del-oro-en-el-anverso-aislado-en-e.jpg?fj=1",
                            Valor = 5000.0
                        },
                        new
                        {
                            MonedaId = 7,
                            Descripcion = "Dogecoin",
                            ImagenUrl = "https://previews.123rf.com/images/architect9/architect92004/architect9200400120/145157172-el-fondo-de-criptomonedas-es-perfecto-para-cualquier-tipo-de-presentaci%C3%B3n-de-noticias-o-informaci%C3%B3n-.jpg?fj=1",
                            Valor = 4000.0
                        },
                        new
                        {
                            MonedaId = 8,
                            Descripcion = "USDCoin",
                            ImagenUrl = "https://www.pngall.com/wp-content/uploads/10/USD-Coin-Logo-PNG-Pic.png",
                            Valor = 3000.0
                        },
                        new
                        {
                            MonedaId = 9,
                            Descripcion = "Terra",
                            ImagenUrl = "https://png.pngtree.com/png-clipart/20220131/original/pngtree-d-front-rendering-cryptocurrency-luna-or-terra-blue-coin-with-cartoon-png-image_7261248.png",
                            Valor = 2000.0
                        },
                        new
                        {
                            MonedaId = 10,
                            Descripcion = "Solana",
                            ImagenUrl = "https://www.pngall.com/wp-content/uploads/10/Solana-Crypto-Logo-PNG-File.png",
                            Valor = 1000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
